version: '3.9'

services:
  darkice:
    image: darkice
    container_name: darkice
    build:
      context: ./darkice
      dockerfile: Dockerfile.darkice
    depends_on:
      - icecast
    devices:
      - "/dev/snd:/dev/snd"
    networks:
      - no-internet
    restart: unless-stopped

  liquidsoap:
    image: liquidsoap
    container_name: liquidsoap
    build:
      context: ./liquidsoap
      dockerfile: Dockerfile
    depends_on:
      - icecast
    devices:
      - "/dev/snd:/dev/snd"
    networks:
      - no-internet
    restart: unless-stopped
    volumes:
      - ./liquidsoap/streaming.liq:/streaming.liq:ro
      - ./liquidsoap/asound.conf:/etc/asound.conf

  icecast:
    image: icecast
    container_name: icecast
    build:
      context: ./icecast
      dockerfile: Dockerfile.icecast
    ports:
      - "8000:8000"
    networks:
      - no-internet
      - internet
    restart: unless-stopped

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
